name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish-github-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Set up npm registry
        run: npm config set registry https://registry.npmjs.org/

      - run: npm install

      - run: npm run build

      - run: npm publish
